### ISSUE TITLE
How do I edit?

### ISSUE THREAD

**Issue by jeandrek** [liam4/the-world-according-to-brian#2]
I can't find the edit button, and trying to push to the wiki gives me a 403:

```
remote: Permission to liam4/the-world-according-to-brian.wiki.git denied to Jonathan50.
fatal: unable to access 'https://github.com/liam4/the-world-according-to-brian.wiki.git/': The requested URL returned error: 403
```

(I'm adding BYOB Tutorials 2 and 3. I also changed the link from byob.berkeley.edu to snap.berkeley.edu...)

**Comment by towerofnix** [comment]
Oops, fixed!

You should be able to edit now.

**Comment by jeandrek** [comment]
I'll try, thanks!

**Comment by jeandrek** [comment]
Works, thanks. Still can't push though.

**Comment by towerofnix** [comment]
Well, I don't use `git` to edit the wiki :P Try re-cloning and pushing?

**Comment by jeandrek** [comment]
I just edited it online :package:

**Comment by towerofnix** [comment]
Cool :P
