### ISSUE TITLE
(net)Hack

### ISSUE THREAD

**Issue by tjvr** [liam4/the-world-according-to-brian#5]
@hardmath123 points out that @bharvey
[indirectly caused nethack](https://en.wikipedia.org/wiki/Lincoln-Sudbury_Regional_High_School#Special_interests) and also is literally all of CS

**Comment by tjvr** [comment]
Bonus data idea: scour the backlinks on his WP page :P

Nice wiki, btw! :-) @liam4

**Comment by towerofnix** [comment]
This is incredible. Thanks for contributing that here, blob :)

I'll probably add it to the readme (and wiki home), since technically it isn't something Brian wrote himself, and would be most apparent at the front of the repository.

**Comment by towerofnix** [comment]
Updated/created these pages:

* [Brian is indirectly the cause of all computer science, the public license, and (Net)Hack](https://github.com/liam4/the-world-according-to-brian/wiki/Brian-is-indirectly-the-cause-of-all-computer-science,-the-public-license,-and-(Net)Hack)
* [Home](https://github.com/liam4/the-world-according-to-brian/wiki)

Again, thanks. :tada:

**Comment by towerofnix** [comment]
Also, it's @brianharvey, not bharvey :)

**Comment by tjvr** [comment]
tnx fam
